# Generated by Django 3.2.3 on 2021-06-24 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marque',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'couleur',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'couleur',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'coût de livraison',
                'verbose_name_plural': 'coûts de livraison',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valeur')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'taux de réduction',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='img')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('price', models.FloatField(verbose_name='prix')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.BooleanField(default=True, verbose_name='disponible')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand', verbose_name='marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='catégorie')),
                ('colors', models.ManyToManyField(to='shop.Color', verbose_name='couleur')),
            ],
            options={
                'verbose_name': 'produit',
            },
        ),
    ]
